name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set PowerShell execution policy
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

      - name: Print environment info
        run: |
          Write-Host "Runner name: $env:RUNNER_NAME"
          Write-Host "Labels: $env:RUNNER_LABELS"
          Write-Host "OS: $env:RUNNER_OS"
          Write-Host "Working Directory: $env:RUNNER_WORKSPACE"

      - name: Do a sample task
        run: |
          Write-Host "Thank you Infinion! My self-hosted runner is LIVE"
          hostname
          Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version
